### ISSUE TITLE
Return after first match

### ISSUE THREAD

**Issue by StijnOostdam** [mganss/AhoCorasick#18]
Hey,

I am using your in a project and am currently implementing an algorithm where we only care for getting any one match.
For example, if we have search patterns `"aa, ab, abc"` and the input string is `"aab"`, then I would only like to know if there is a match and I do not care if it is either `"aa"` or `"ab"`. So essentially just the search function, which returns its first match. I think this can be a major performance improvement for my case. Could you let me know if you are willing to include this in your library? I can see why you would not like this, as it kind of goes against the main idea of the AhoCorasick algorithm, but it would be nice to have for me.

**Comment by mganss** [comment]
This should be possible with the current code. Search results are returned one at a time. So:

```c#
var anyMatch = new AhoCorasick("aa", "ab", "abc").Search("aab").Any();
```

`Any()` will stop iterating once the first element has been found.

**Comment by StijnOostdam** [comment]
I see, I now understand the use case of `yield return`. Then I will just use `.First()`, thanks!

**Comment by mganss** [comment]
`First()` will throw if there is no match, so you might want to use `FirstOrDefault()` instead.

**Comment by StijnOostdam** [comment]
Yeah, I thought about that. But since `WordMatch` is a struct, it cannot be null, so `FirstOrDefault()` would not work either I think. I ended up with:

`return matches.Any() ? Matches.First().Word : null`

**Comment by mganss** [comment]
I think this will iterate twice. Using `FirstOrDefault` should work because the default value of `WordMatch` is an object with `Index == 0` and `Word == null`.

**Comment by StijnOostdam** [comment]
`FirstOrDefault` works great, thanks!
