### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by Bia10** [mganss/AhoCorasick#36]
any clue how to handle this, is the input in wrong format or what's goin on here? :)

![image](https://user-images.githubusercontent.com/2548763/126908351-5e8d365c-3067-43c6-b356-5718017d1362.png)

**Comment by mganss** [comment]
I have a feeling there's an empty string in the list. There needs to be at least one character to search for. Admittedly, the exception should be more helpful.

If this is not the case, please attach a demo file to this issue.

**Comment by Bia10** [comment]
Yes that was the problem thanx
