### ISSUE TITLE
How long will it take to create the trie tree? 

### ISSUE THREAD

**Issue by tonyqus** [mganss/AhoCorasick#56]
Did you benchmark how long it will take to create the trie tree if there are many words (eg. 5000words)? This algorithm is useful in dirty/censorship words matching. But usually, the words list can be very long and dynamic (maintainable).

**Comment by mganss** [comment]
I've done an adhoc test on my desktop machine with 5000 random words of 1-10 characters in length and it takes ~8ms to build the trie. Though IMO this is pretty fast it shouldn't matter all that much because the typical use case is to build the tree once, then perform the matching many times.
