### ISSUE TITLE
BuildFail generates considerable amount of garbage

### ISSUE THREAD

**Issue by gzatravkin** [mganss/AhoCorasick#85]
![image](https://github.com/user-attachments/assets/79ae5621-f93b-4c80-ac4f-de80de8184bd)
When you do BuildFail (due to adding new words to the list) it generates considerable amount of garbge because of line

`                node.Fail = Trie.ExploreFailLink(word.Substring(i));`

**Comment by mganss** [comment]
Fixed by #86
